pipeline {
    agent any

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    stages {
        stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }
        stage('Build') {
          steps {
            script {
              sh 'echo "Building Stage"'
            }
          }    
        }
        stage('SCM Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/eoumenwa/ansible-project.git'
            }
        }
        stage('Execute Ansible') {
            steps {
                ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'ansible-project/inventory/${inventory}', playbook: 'playbooks/nginx.yml'
            }
        }
    }
}