---
- hosts: all
- name: Include dynamic variables 
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: db
- name: Mysql db assignment
  import_playbook: ../static-assignments/mysql.yml




   