---
- hosts: all
- name: include dynamic variables 
  import_playbook: ../static-assignments/mysql.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: database
- name: Mysql db assignment
  import_playbook: ../static-assignments/mysql.yml




   